<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="user.xsd"/>
	<xs:annotation>
		<xs:appinfo>
			<xs:documentation>
			Valida os utilizadores para "authentication &amp; authorization"
			</xs:documentation>
		</xs:appinfo>
	</xs:annotation>
	<xs:element name="users">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="user" type="userType" minOccurs="1"	maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:key name="pk_userid">
		<xs:selector xpath="user/userid" />
		<xs:field xpath="." />
	</xs:key>
	<xs:unique name="ak_username">
		<xs:selector xpath="user/username" />
		<xs:field xpath="." />
	</xs:unique>
	<xs:unique name="ak_email">
		<xs:selector xpath="user/email" />
		<xs:field xpath="." />
	</xs:unique>
</xs:element>
</xs:schema>







