<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="nationality.xsd" />
	<xs:annotation>
		<xs:appinfo>
			<xs:documentation>
				Tipos de dados associados a um utilizador
			</xs:documentation>
		</xs:appinfo>
	</xs:annotation>
	<xs:complexType name="remoteUserType">
		<xs:annotation>
			<xs:appinfo>
				<xs:documentation>
					Define o tipo que carateriza um utilizador, usado remotamente
				</xs:documentation>
			</xs:appinfo>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="basicType">
				<xs:sequence>
					<xs:element name="full-nationality"
						type="nationalityType" />
					<xs:element name="full-name" type="fullNameType" />
					<xs:element name="age" type="ageType" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="userType">
		<xs:annotation>
			<xs:appinfo>
				<xs:documentation>
					Define o tipo que carateriza um utilizador, registado localmente
				</xs:documentation>
			</xs:appinfo>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="basicType">
				<xs:sequence>
					<xs:element name="password" type="passwordType">
						<xs:annotation>
							<xs:appinfo>
								<xs:documentation>Hash da Senha</xs:documentation>
							</xs:appinfo>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="basicType">
		<xs:annotation>
			<xs:appinfo>
				<xs:documentation>
					Define o tipo que carateriza um utilizador, usado localmente
				</xs:documentation>
			</xs:appinfo>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="userid" type="UUIDType">
				<xs:annotation>
					<xs:appinfo>
						<xs:documentation>Identificador</xs:documentation>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
			<xs:element name="updated" type="xs:dateTime">
				<xs:annotation>
					<xs:appinfo>
						<xs:documentation>Data da última atualização</xs:documentation>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
			<xs:element name="blocked" type="xs:boolean">
				<xs:annotation>
					<xs:appinfo>
						<xs:documentation>Indica que está bloqueado</xs:documentation>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
			<xs:element name="profile" type="profileType">
				<xs:annotation>
					<xs:appinfo>
						<xs:documentation>Número que define o perfil</xs:documentation>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
			<xs:element name="username" type="userNameType">
				<xs:annotation>
					<xs:appinfo>
						<xs:documentation>Nome curto, alcunha ou nickname
						</xs:documentation>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
			<xs:element name="firstnames" type="nameType">
				<xs:annotation>
					<xs:appinfo>
						<xs:documentation>Primeiros nomes</xs:documentation>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
			<xs:element name="lastnames" type="nameType">
				<xs:annotation>
					<xs:appinfo>
						<xs:documentation>Últimos nomes</xs:documentation>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
			<xs:element name="email" type="emailType">
				<xs:annotation>
					<xs:appinfo>
						<xs:documentation>Endereço de correio eletrónico
						</xs:documentation>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
			<xs:element name="gender" type="genderType" minOccurs="0">
				<xs:annotation>
					<xs:appinfo>
						<xs:documentation>Género do utilizador</xs:documentation>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
			<xs:element name="birthdate" type="xs:date" minOccurs="0">
				<xs:annotation>
					<xs:appinfo>
						<xs:documentation>Data de nascimento (data do passado)
						</xs:documentation>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
			<xs:element name="photography" type="photoType"
				minOccurs="0">
				<xs:annotation>
					<xs:appinfo>
						<xs:documentation>
							Fotografia tipo passaporte: 35x45 mm (300 x 300
							pixels) ver
							https://pt.idphoto4you.com/
							- Uma foto recente do rosto
							do utilizador a olhar para a câmera.
							- Ter um fundo branco ou
							cinza claro.
							- Ter boa iluminação e nitidez.
							- Incluir a parte
							superior da cabeça e ombros.
							- O utilizador não deve usar óculos
							de sol, chapéu ou outros
							acessórios que cubram o rosto.
						</xs:documentation>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
			<xs:element name="nationality" type="abbreviationType"
				minOccurs="0">
				<xs:annotation>
					<xs:appinfo>
						<xs:documentation>Nacionalidade: ISO Country Codes Alpha-2 ver
							https://www.iban.com/country-codes
						</xs:documentation>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="UUIDType">
		<xs:annotation>
			<xs:appinfo>
				<xs:documentation>
					Valida um UUID (Universally Unique Identifier) que
					identifica um utilizador
				</xs:documentation>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern
				value="[0-9a-f]{8}-[0-9a-f]{4}-[0-4][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="profileType">
		<xs:annotation>
			<xs:appinfo>
				<xs:documentation>
					Valida o tipo de perfil, assume que é valor 0..10
				</xs:documentation>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:short">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="10" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="userNameType">
		<xs:annotation>
			<xs:appinfo>
				<xs:documentation>
					Valida nome curto ou nickname de um utilizador
				</xs:documentation>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:pattern value="[a-zA-Z0-9_-]{4,10}" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="passwordType">
		<xs:annotation>
			<xs:appinfo>
				<xs:documentation>
					Informação cifrada sobre a password em MD5 ou SHA:
					MD5 (Message-Digest Algorithm 5) é um algoritmo mais antigo, que
					gera
					uma string de 128 bits.
					SHA (Secure Hash Algorithm) é uma
					família de algoritmos mais recentes
					e seguros,
					que geram strings de
					tamanhos diferentes dependendo da versão usada.
					Por exemplo, SHA-1
					gera uma string de 160 bits e SHA-256 gera uma
					string de 256 bits.
				</xs:documentation>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:minLength value="32" />		<!-- MD5 128 bits, 32 carateres hexadecimais -->
			<xs:maxLength value="64" />		<!-- SHA 256 bits, 64 carateres hexadecimais -->
		</xs:restriction>

	</xs:simpleType>
	<xs:simpleType name="nameType">
		<xs:annotation>
			<xs:appinfo>
				<xs:documentation>
					Valida nomes próprios ou aplelidos de um
					utilizador
				</xs:documentation>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Zà-úÀ-Ú\s'-]{1,60}" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="fullNameType">
		<xs:annotation>
			<xs:appinfo>
				<xs:documentation>
					Valida nome completo de um utilizador
				</xs:documentation>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Zà-úÀ-Ú\s'-]{1,120}" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="emailType">
		<xs:annotation>
			<xs:documentation>
				Valida um endereço de correio eletrónico.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern
				value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ageType">
		<xs:annotation>
			<xs:appinfo>
				<xs:documentation>
					Valida a idade (em anos) de um utilizador
				</xs:documentation>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:short">
			<xs:minInclusive value="3" />
			<xs:maxInclusive value="130" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="genderType">
		<xs:annotation>
			<xs:appinfo>
				<xs:documentation>
					Valida o género de um utilizador 'M'-Male;
					'F'-Female; 'X'-Indefinido
				</xs:documentation>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:pattern value="[MFX]" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="photoType">
		<xs:annotation>
			<xs:appinfo>
				<xs:documentation>
					Valida a fotografia representada em base64 (não
					inclui: data:image/jpg;base64,)
				</xs:documentation>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:base64Binary">
			<xs:minLength value="4096" />
			<xs:maxLength value="209715" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>







